apiVersion: v1
kind: Namespace
metadata:
  name: blog-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: halo-config
  namespace: blog-system
data:
  HALO_EXTERNAL_URL: "http://localhost:8090"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-pvc
  namespace: blog-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halo
  namespace: blog-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halo
  template:
    metadata:
      labels:
        app: halo
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: halo-data
          persistentVolumeClaim:
            claimName: halo-pvc
      containers:
        - name: halo
          image: registry.fit2cloud.com/halo/halo:2.21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
              name: http
          env:
            - name: JVM_OPTS
              value: "-Xms256m -Xmx512m"
            - name: HALO_WORK_DIR
              value: /root/.halo2
            - name: HALO_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: halo-config
                  key: HALO_EXTERNAL_URL
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          args:
            - --spring.r2dbc.url=r2dbc:pool:mysql://mysql.blog-system.svc.cluster.local:3306/$(MYSQL_DATABASE)
            - --spring.r2dbc.username=$(MYSQL_USER)
            - --spring.r2dbc.password=$(MYSQL_PASSWORD)
            - --spring.sql.init.platform=mysql
            - --halo.external-url=$(HALO_EXTERNAL_URL)
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
            - name: halo-data
              mountPath: /root/.halo2
---
apiVersion: v1
kind: Service
metadata:
  name: halo
  namespace: blog-system
spec:
  selector:
    app: halo
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP
